### ISSUE TITLE
Attempted import error: 'FormState' is not exported from 'informed'.

### ISSUE THREAD

**Issue by RajaTheKing826** [joepuzzo/informed#368] opened 2021-12-14 04:19 UTC
I have updated the informed package version from 3.34.0 to 4.0.8 and now I am getting this error. Is there any fix for this? I have tried out version 4.0.9 also it is also leading to the same issue?

![Screenshot from 2021-12-14 09-43-54](https://user-images.githubusercontent.com/59301270/145932221-54d9d8bf-d59c-465f-94d1-01107ee473d4.png)

Getting the above error in my ts file. 

Getting **Attempted import error: 'FormState' is not exported from 'informed'.** error while I am trying to import the **FormState** in a js file.

Any fix for this?

**Comment by Bezmehrabi** [comment] 2021-12-14 06:19
`FormState` component is gone. but you can create it for yourself if you want.
there are now 2 ways to access form state: 

1.  using `useFormState` hook: 
 ```js

function FormState() {
    const formState = useFormState()

    return (
      <pre>
        <code>{JSON.stringify(formState, null, 2)}</code>
      </pre>
   )
}
```
2. using the new `FormStateAccessor` component:
```js
function FormState() {
  return (
    <FormStateAccessor>
      {formState => (
         <pre>
           <code>{JSON.stringify(formState, null, 2)}</code>
         </pre>
      )}
   </FormStateAccessor>
  )
}
```

**Comment by RajaTheKing826** [comment] 2021-12-14 06:29
Ok, Thanks for the solution, But I am getting errors for Form, Multiestep components also 

![Screenshot from 2021-12-14 11-57-50](https://user-images.githubusercontent.com/59301270/145944985-058b43a8-433e-4c76-b7a3-d910b9231ae9.png)


do we have to write all these components?

**Comment by Bezmehrabi** [comment] 2021-12-14 06:34
sorry I miss lead you about `FormState`, the component name has changed to `Debug`.
so instead of  `FormState', import `Debug` component and use that.

```js
import { Debug } from 'informed'

function MyForm() {
   return (
       <Form>
           <Debug /> 
       </Form>
   )
}

```

**Comment by Bezmehrabi** [comment] 2021-12-14 06:42
You definitely don't need to write all this.
The TS declaration file of the library is not complete, so these components actually exist, but typescript doesn't know about them, so TS shows you these errors.

You temporarily need to ignore these typescript errors.
We are working on updating the declaration file, And when that's done, your issue will be resolved.

**Comment by joepuzzo** [comment] 2021-12-14 06:44
Yes TS is not fully complete. The library is however. So td ignore until all are added.

**Comment by RajaTheKing826** [comment] 2021-12-14 09:36
Thanks for the response dude :)

**Comment by joepuzzo** [comment] 2021-12-16 02:21
Closing as we have resolved ( will add more types )

**Closed by joepuzzo** 2021-12-16 02:21 UTC

**Comment by wahlstedt** [comment] 2021-12-20 22:27
I think this issue should remain open until the TS definitions are back in place. I had the same problem and couldn't find the cause until I checked closed issues.
