### ISSUE TITLE
setValue and setTouched of both formApi and fieldApi hooks are not working in the version 4.0.8 

### ISSUE THREAD

**Issue by SoloDev45** [joepuzzo/informed#370] opened 2021-12-15 05:17 UTC
I have updated the informed version to 4.0.8. Now when I'm using the setTouched method from formApi Hook it shows an error like **TypeError: Cannot read properties of undefined (reading 'validate')**.

How can I resolve the issue? And while trying to change a field value using setValue from both useField and formApi hook, the value is not getting changed.

How can I resolve the issue?

**Comment by Bezmehrabi** [comment] 2021-12-15 10:39
could you please provide a reproducible code sandbox?

**Comment by joepuzzo** [comment] 2021-12-15 23:27
What he said ^^

**Comment by SoloDev45** [comment] 2021-12-16 03:52
> could you please provide a reproducible code sandbox?
This is the code sandbox link. In this code, while I'm moving from step-2 to step-1 I am clearing the field value in the first step but the value is not changing.

you can check the code in `onPrevious` method.

https://codesandbox.io/s/sharp-goldwasser-6kfhe

**Comment by joepuzzo** [comment] 2021-12-16 03:55
I know what the issue is

**Comment by joepuzzo** [comment] 2021-12-16 03:55
I forgot to document a slight breaking change. Every step in multistep is now "scoped" to its step="secondStep"

**Comment by joepuzzo** [comment] 2021-12-16 03:57
Hmm but still seems to be issue with setTouched.. let me look into it

**Comment by joepuzzo** [comment] 2021-12-16 04:03
Also before I get too in the weeds please read migration docs in CHANGELOG

1. You are using `validationSchema` instead of `yupSchema`
2. You are using `validateOnBlur` and `validateOnChange` instead of `validateOn="change"`

**Comment by joepuzzo** [comment] 2021-12-16 04:06
I have solve ( small null check bug ) for the setTouched issue! I will get that out and update the code sandbox

**Comment by SoloDev45** [comment] 2021-12-16 04:11
> I forgot to document a slight breaking change. Every step in multistep is now "scoped" to its step="secondStep"

In the second step also it is not working I have updated my code in the code sandbox you can have a look into it

**Comment by joepuzzo** [comment] 2021-12-16 04:14
https://codesandbox.io/s/multie-step-practice-forked-9kqoe?file=/src/App.js

**Comment by joepuzzo** [comment] 2021-12-16 04:16
Working code sandbox ^^^

**Comment by joepuzzo** [comment] 2021-12-16 04:16
Im assuming you want to also clear the error out ( same solve for that too )

**Comment by joepuzzo** [comment] 2021-12-16 04:17
```js
 const onPrevious = () => {
    // Note how because im NOT in the context of the step, I must prefix with `stepName` `secondStep` in this case
    formApi.setValue("secondStep.secondName", "");
    formApi.setTouched("secondStep.secondName", undefined);
    previous();
  };
```

**Comment by SoloDev45** [comment] 2021-12-16 04:20
> Working code sandbox ^^^

Yess !! it's working fine now. Thanks :tada:

**Comment by joepuzzo** [comment] 2021-12-16 04:29
Cool Closing !

**Closed by joepuzzo** 2021-12-16 04:29 UTC
