### ISSUE TITLE
Validation on ArrayField fails after removing a row

### ISSUE THREAD

**Issue by gaelph** [joepuzzo/informed#240] opened 2019-08-12 15:19 UTC
Hi,

When using ArrayFields with multiple fields in it, form validation fails awkwardly after removing a row.
You can see an example of this problem on [this codesandbox](https://codesandbox.io/s/happy-bose-xzjze)
following these steps:

 1. Type anything in the two inputs
 2. Add a new line, and let them empty
 3. Click `submit`
 4. Remove the second line
 5. You can see an error message displayed next to the second input of the first line, but that input is valid!

From what we observed, it looks like upon deletion, the validation works only for the first input with a `validate` function in the row, and fails for the others, no matter their content.

**Comment by joepuzzo** [comment] 2019-09-10 14:37
Confirmed. This is a tuff one and I have not had the time lateley to look into. I will soon. Def looks like a bug tho

**Comment by joepuzzo** [comment] 2020-02-27 03:37
This is fixed in the latest version.

**Closed by joepuzzo** 2020-02-27 03:37 UTC
